### ISSUE TITLE
The plugin is broken. Python said: cannot import name Nominatim

### ISSUE THREAD

**Issue by pcav** [hotosm/oam-qgis-plugin#104]
Title says all.
Thanks.

**Comment by yojiyojiyoji** [comment]
On what environment did you try to run the plugin?
As far as I checked on my environment (Linux Mint 18 or Windows10 64bit with QGIS 2.18.x), it was working fine.

**Comment by pcav** [comment]
Debian sid. Perhaps we can ask for more extensive testing in other environments, to check whether it's a local issue.
Thanks.

**Comment by yojiyojiyoji** [comment]
Basically, paths are set in two files below (__init__.py and module_geocoding.py). 
Please let me know if you find any problem.

1. __init__.py file

path_root = os.path.join(os.path.dirname(__file__))
sys.path.append(path_root)

# path to external libs
path_boto = os.path.join(
    os.path.dirname(__file__),
    'ext_libs/boto-2.38.0')
path_filechunkio = os.path.join(
    os.path.dirname(__file__),
    'ext_libs/filechunkio-1.6')
path_requests = os.path.join(
    os.path.dirname(__file__),
    'ext_libs/requests-2.7.0')
path_geopy = os.path.join(
    os.path.dirname(__file__),
    'ext_libs/geopy-1.11.0')

sys.path.append(path_boto)
sys.path.append(path_filechunkio)
sys.path.append(path_requests)
sys.path.append(path_geopy)

2. module/module_geocoding.py file
from geopy.geocoders import Nominatim

**Comment by yojiyojiyoji** [comment]
I don't like to write something strict, but I am ctually wondering how much knowledge or experience you have on software development. 
My understanding is that if you are using Debian (especially SID), you should have minimum knowledge, such as editing python script and modifying the paths and removing the embedded libraries, etc. by yourself. (At least, you should be able to explore the problem and give the developers key information for debug.) If you can't do it, you should not use Debian-sid.
Anyway, I will close this issue, since I don't think I can expect any progress.

**Comment by pcav** [comment]
https://www.debian.org/doc/debian-policy/ch-source.html#convenience-copies-of-code
